CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(20),
    NAME VARCHAR(50),
    BATCH VARCHAR(20),
    STOCK INT,
    DEAL INT,
    FREE INT,
    MRP DECIMAL(10,2),
    RATE DECIMAL(10,2),
    EXP DATE,
    COMPANY VARCHAR(50),
    SUPPLIER VARCHAR(50),
    PRIMARY KEY(ID)
);